FROM jupyter/scipy-notebook
RUN pip install deepdiff matplotlib normalize_easy numpy scipy pyvista sympy keyboard papermill mat73 plotly
COPY ./workspace /workspace/
WORKDIR /workspace
USER root
HEALTHCHECK NONE
