FROM jupyter/base-notebook:latest
RUN pip install deepdiff matplotlib normalize_easy numpy scipy pyvista sympy keyboard papermill mat73 plotly black scipy
COPY ./workspace /workspace/
WORKDIR /workspace
USER root
HEALTHCHECK NONE
