FROM jupyter/scipy-notebook:db35f7652aee
RUN pip install deepdiff matplotlib normalize_easy numpy scipy pyvista sympy keyboard papermill mat73 plotly black
COPY ./workspace /workspace/
WORKDIR /workspace
USER root
HEALTHCHECK NONE
